name: deploy staging to render

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.PRODUCTION_SERVICE_KEY }}
          api_key: ${{ secrets.API_TOKEN }}
          wait_deploy: true
